# Site settings
title: Abdullah Saleem
subtitle: "Eat, Sleep and Breathe Code"
email: a.saleem2993@gmail.com
description: "I <3 Sasha"
baseurl: ""
url: "http://abdullahsaleem.me"
twitter_username: "abdullah2993"
github_username:  "loyaltyHF"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed